# Generated by Django 5.1.2 on 2024-11-02 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='invited_users',
            field=models.ManyToManyField(blank=True, related_name='invitations', to=settings.AUTH_USER_MODEL),
        ),
    ]
