# Generated by Django 5.1.2 on 2024-11-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_initial'),
        ('problems', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='problems',
            field=models.ManyToManyField(to='problems.problem'),
        ),
    ]
